version: '3.7'

services:
  app:
    image: node:20-alpine
    command: sh -c "npm install && npm run dev"
    restart: always
    container_name: node
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: quizz
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: